# Generated by Django 5.0.4 on 2024-04-13 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_cards_userlangauth_user_alter_order_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='card_id',
        ),
        migrations.DeleteModel(
            name='Cards',
        ),
    ]
