# Generated by Django 5.0.4 on 2024-04-13 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_remove_payment_card_id_delete_cards'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=16)),
                ('type', models.CharField(choices=[('Humo', 'Humo'), ('Uzcard', 'Uzcard'), ('Visa', 'Visa')], max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='card_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.cards'),
        ),
    ]
