# Generated by Django 5.0.4 on 2024-04-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_cards_payment_card_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userlangauth',
            name='tg_user_id',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
