# Generated by Django 5.0.4 on 2024-04-14 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_order_gamer_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
